version: 2.1
orbs:
  maven: circleci/maven@1.4.1
workflows:
 maven Project:
   jobs:
     - test
jobs:
  test:
    docker:
      - image: cimg/openjdk:20.0.1
    steps:
      - checkout
      - run: 
          name: maven build
          command: |
          sudo apt-get update && sudo apt-get install openjdk-17-jdk
          java -version
          
        
