version: 2.1
orbs:
  maven: circleci/maven@1.4.1
workflows:
 maven Project:
   jobs:
     - test
jobs:
  test:
    docker:
      - image: circleci/openjdk:17-ea-33-buster-node-browsers-legacy
    steps:
      - checkout
      - run: 
          name: maven build
          command: |
          sudo apt-get update && sudo apt-get install openjdk-17-jdk
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
          java -version
          
        
