version: 2.1
orbs:
  maven: circleci/maven@1.4.1
workflows:
 maven Project:
   jobs:
     - test
jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: java -version
    
          
          
        
