version: 2.1

workflows:
 test-deploy:
   jobs:
     - test
jobs:
  test:
    docker:
      - image: circleci/openjdk:17-ea-33-buster-node-browsers-legacy
    steps:
      - checkout
      - run: java --version
