name: SonarQube Analysis
 
on:
  push:
    branches:
      - master  # Run analysis on push to the 'main' branch
  pull_request:
    branches:
      - master  # Run analysis on pull requests targeting the 'main' branch
 
jobs:
  sonarQube:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      # Set up JDK for Java projects (optional, adjust as needed)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
 
      - name: SonarQube Scan
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=thaadur_WebGoat_87eeb9f6-a2b1-43c8-9b7b-fea6a5ab3062
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
